#!/usr/bin/env python
import os
import sys

prefix = '/opt/ml/'

input_path = prefix + 'input/data'
output_path = os.path.join(prefix, 'output')
model_path = os.path.join(prefix, 'model')


# The function to execute the training.
def train():
    print('\nStarting the training.')
    with open(os.path.join(model_path, 'model'), 'w') as f:
        f.write('dummy model params');
    print('Training complete.')


if __name__ == '__main__':
    train()
    sys.exit(0)
